# Generated by Django 2.0.3 on 2018-03-25 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 25, 11, 27, 40, 193577, tzinfo=utc), verbose_name='date published'),
        ),
    ]
